### ISSUE TITLE
Verium Wallet - Capital letters with "shift" key not working when entering password

### ISSUE THREAD

**Issue by MaciejTXFive** [VeriumReserve/verium#105]
Sorry, not sure where to put this issue, so I put it here, feel free to move it later.

Device: Macbook Pro, Mac OS Catalina

The issue:
When you keep shift key and try to type capital letter for password, nothing happens. I catched myself couple times trying to type in password, and ended up copying-pasting. That way it works. I guess some other people may have problems with it, and be afraid they lose access to their wallet.

**Comment by mderasse** [comment]
Hi,

Thank you for the bug report !

The issue will be fix in the verium vault 1.3.0 that should be release soon.

I will keep that issue open until we release and confirm the issue is fixed

**Comment by mderasse** [comment]
Hi, we just released the Verium Vault v1.3.1. That should fix your issue.
Can you give it a try and confirm ?

Thank you
