### ISSUE TITLE
Community tab wrong slack link

### ISSUE THREAD

**Issue by mathiastro** [VeriumReserve/verium#129]
Version 1.3.1

Windows-qt

When clicking the icon for "Chat" you will be directed to "https://slackin-idqpjecyzv.now.sh/" - Should be "http://slack.vericoin.info"

**Comment by mderasse** [comment]
There is no issue in the wallet,
Basically, slack.vericoin.info redirect to https://slackin-idqpjecyzv.now.sh/ (which is broken, but that's another problem ...)
