### ISSUE TITLE
Add Dockerfile to project

### ISSUE THREAD

**Issue by dennisvanderpool** [VeriumReserve/verium#133]
Just what the title mentions. I would like to host a verium node by running it in docker. Would like to have Docker being part of the project.

This is my work in progress, which fails because it can't find the db4_cxx.h even though i disable wallet support:

FROM ubuntu:latest

RUN apt update -y && \
    apt upgrade -y

RUN apt-get install -y git

# install packages needed to build vericoind
RUN apt install -y \
        build-essential \
        libtool \
        autotools-dev \
        automake \
        pkg-config \
        libssl-dev \
        libevent-dev \
        bsdmainutils \
        libcurl4-openssl-dev \
        zlib1g-dev \
        libminizip-dev \
        libboost-all-dev
# python3

# install additional packages
RUN apt install -y iftop lsb-release multitail pax-utils tree unzip vim wget

RUN git clone -v https://github.com/VeriumReserve/verium.git ~/verium

# install Berkeley DB 4.8
RUN cd ~/verium && \
        ./contrib/install_db4.sh ~/verium

# configure build
RUN export BDB_PREFIX="${HOME}/verium/db4" && \
        cd ~/verium/ && \
        ./autogen.sh && \
        ./configure --disable-wallet \
                    --enable-hardening \
                    --without-gui \
                    --without-miniupnpc \
                    --with-pic \
                    --prefix=$BDB_PREFIX \
                    BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" \
                    BDB_CFLAGS="-I${BDB_PREFIX}/include"

# run the build
RUN cd ~/verium/ && \
        make && \
        make install

RUN cp ~/verium/src/veriumd /usr/bin/

RUN strip /usr/bin/veriumd

EXPOSE 36988

CMD ["veriumd"]

**Comment by mderasse** [comment]
Hi,

You can find a docker repository on https://github.com/VeriConomy/docker-veriumd

We will also move the verium repository there in a few months
