### ISSUE TITLE
Include hash for official binaries

### ISSUE THREAD

**Issue by TnTBass** [VeriumReserve/verium#136]
The binaries available on https://files.vericonomy.com/vrm/ are great, but there are no hashes available for any binary uploaded there.  If md5, sha-1, sha-256 are available, we could verify the hash against the binary to ensure the binary is secure.

**Comment by effectsToCause** [comment]
This is on the list of todos

**Comment by mderasse** [comment]
Hi,

Added on https://files.vericonomy.com/vrm/

**Comment by TnTBass** [comment]
Any chance these can be split up per file?  Alpine Linux doesn't include the ability to '--ignore-missing' which means the hash check fails when validating against the file.

```
/ # sha512sum -c --ignore-missing SHA512SUMS
sha512sum: unrecognized option: ignore-missing
/ # sha512sum -c SHA512SUMS -s
sha512sum: can't open 'verium-1.3.1-aarch64-linux-gnu.tar.gz': No such file or directory
sha512sum: can't open 'verium-1.3.1-arm-linux-gnueabihf.tar.gz': No such file or directory
sha512sum: can't open 'verium-1.3.1-i686-pc-linux-gnu.tar.gz': No such file or directory
sha512sum: can't open 'verium-1.3.1-win64-unsigned.zip': No such file or directory
sha512sum: can't open 'Verium_Vault-1.3.1-Linux-32bits.AppImage': No such file or directory
sha512sum: can't open 'Verium_Vault-1.3.1-Linux-64bits.AppImage': No such file or directory
sha512sum: can't open 'Verium_Vault-1.3.1-MacOS.pkg': No such file or directory
sha512sum: can't open 'Verium_Vault-1.3.1-Win64-Unsigned.exe': No such file or directory
/ # echo $?
1
```

This is a pain since Ubuntu works fine, since I can ignore the missing files.  
My only other option is to download every binary contained in the hash files, then purge the ones I don't need.

**Comment by TnTBass** [comment]
While I'd still prefer a per file checksum, I have worked around it for now.  Thanks team!
