### ISSUE TITLE
Start Wallet Miner with cli version

### ISSUE THREAD

**Issue by ccnorth** [VeriumReserve/verium#148]
the comand: "verium-cli minerstart 1 "  not worked 

 the Miner start only with : curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "minerstart", "params": [1] }' -H 'content-type: text/plain;' http://127.0.0.1:33987/   

And take Mining Arguments like --ryzen or AVX/AVX2 for that. an Version 1.3.2 the Miner start only with AVX . On intel CPUs decrease the Hashrate over 50%  Example: My 12core Xeon mined only with 2800H/m 24threads on version 1.3.2. with FirewormMiner coded with Avx2 it mined with 5400H/m

**Comment by Calvario** [comment]
Hello,
The fix will be available when a new version of the wallet will be published.
