### ISSUE TITLE
getwork is invalid from cpuminer (per the wiki's instructions)

### ISSUE THREAD

**Issue by genewitch** [VeriumReserve/verium#157]
I have rpc working over my network, and i can do minerstart, etc locally. When i run cpuminer (effectstocause version, as well as 1.3 and 1.4) with -P:
`[2021-04-24 10:32:07] JSON protocol request:
{"method": "getwork", "params": [], "id":0}
`
then the http header dump, then the json response is:
`[2021-04-24 10:32:07] JSON protocol response:
{
   "error": {
      "message": "Method not found",
      "code": -32601
   },
   "result": null,
   "id": 0
}
`

now, there exist verium pools, so i know it's possible (somehow) to mine in a pool, is solo mining disabled against veriumd? 

I've tried this on linux with CLI only and windows with the GUI.

if i do --no-stratum --no-getwork i get an error 
`Unrecognized block version: 7`

Sorry if this is a mishmash, i've been trying to get this to work for a month or two on various platforms. I've previously run mining pools (including with stratum) - so i'm at a loss, here. it seems like my verium wallets are broken or misconfigured.

**Comment by mderasse** [comment]
Hi,

Getwork doesn't exist anymore on the new verium wallet.

Right now only that miner is compatible:
https://github.com/VeriConomy/veriumMiner/commits/master
You will have to compile it

I'm sorry that our doc is not up to date. We are currently working on releasing a new version of our wallet (verium & vericoin) and rewriting all the doc. i hope that we can finish that quickly.

Let me know if you need further help

**Comment by genewitch** [comment]
I'll check it out, i meant to do this earlier but it got too hot to mine.

Thank you!
